local tips={
    "Ohh. Ohhhhh!",
    "Feels... Techmino... gameplay...",
    "Push what, idk",
    "Don't you pretend you suck",
    "Even a dog can sub30",
    "c4w so cool",
    "Wowwwww!!!",
    "Lua no. 1",
    "Aquamarine is just a block game player, he knows no code",
    "Bad argument #6623:Attempt to compare number with nil",
    "I'm a placeholder",
    "Insert Genshin Impact joke that can't translate",
    "SDPC not followed by DPC, what do I do without the spike",
    "Aquamarine here, I talk nonsense in the tips",
    "Anyways it's not the first block game to have tips",
    "A Project by TEAM BLANKER",
    "Game's birthday? I made it summer 2023, so let's say August 14",
    "Z Review: \"Pretty decent Techmino ripoff\"",
    "Carbon Fibre skin is inspired by Rubik's cubes with those stickers",
    "Aquamino's Sokoban Minigame",
    "Aqua in the name doesn't mean everything related to water",
    "SRS here modified, with symmetric I and 180 kicks"
}
return tips