local tips={
    "",
    "Ohh. Ohhhhh!",
    "Maybe it's just me getting high",
    "Damn, that's something",
    "Feels... Techmino... gameplay...",
    "O-spin what, idk",
    "Don't you pretend you suck",
    "Even a dog can sub30!",
    "Wowwwww!!!",
    "Lua no. 1",
    "Aquamarine is just a block game player, he knows no code",
    "but Techmino still more famous",
    "Aquamino chat is full of some other mino lol",
    "Aquamino not fun",
    "#h.studio <include>",
    "Send feedback to mintechoaqua@163.com",
    "Error main.lua:6623: attempt to compare boolean with number",
    "Insert joke about infinite decimal in binary division",
    "sub14 when",
    "It's stuck here...",
    "head empty...",
    "Play less blocks, read more books"
}
return tips